name: Coverage
on:
  pull_request:
    paths:
      - "*.js"
      - "*.ts"
      - "*-lock.yaml"
      - "package.json"
      - "packages/**/*-lock.yaml"
      - "packages/**/*.js"
      - "packages/**/*.ts"
      - "packages/**/package.json"
      - ".github/workflows/coverage.yml"
      - "!docs/**"
      - "!website/**"
  push:
    branches:
      - main
    paths:
      - "**/package.json"
      - "**/*-lock.yaml"
      - "**/*.ts"
      - "**/*.js"
      - ".github/workflows/coverage.yml"
      - "!docs/**"
      - "!website/**"

permissions:
  contents: read

jobs:
  coverage:
    permissions:
      checks: write # for coverallsapp/github-action to create new checks
      contents: read # for actions/checkout to fetch code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: pnpm

      - run: pnpm -v

      - run: pnpm i
      - run: pnpm run build
      - run: pnpm run coverage

      - name: Upload coverage Coveralls
        uses: coverallsapp/github-action@9ba913c152ae4be1327bfb9085dc806cedb44057 # 1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@54bcd8715eee62d40e33596ef5e8f0f48dbbccab # v3
        with:
          directory: "."
          files: ./lcov.info
