name: cSpell TS/MD
on:
  pull_request:
    paths:
      - "**/*.md"
      - "**/*.ts"
      - "cspell-dict.txt"
      - "cspell.json"
  push:
    branches:
      - master
    paths:
      - "**/*.md"
      - "**/*.ts"
      - "cspell-dict.txt"
      - "cspell.json"

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: npx cspell "**/*.*"
