# https://github.com/dependabot/dependabot-core/issues/1736
name: Dependabot - Process Recreate Pull Requests
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

permissions: read-all

jobs:
  add-comment-recreate:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Show Event Data
        env:
          PR_DATA: ${{ toJSON(github.event) }}
        run: |
          echo "$PR_DATA"

      - name: Show Open PRs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr list -S "author:app/dependabot"

      - name: Has PRs in progress?
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo PR_IN_PROGRESS=$(
            gh pr list -S "label:dependabot:recreate-in-progress author:app/dependabot" --json number | jq -r 'if .[0] then .[0].number else "" end'
          ) >> $GITHUB_ENV

      # time is up, remove label.
      - name: Remove in-progress label
        if: ${{ env.PR_IN_PROGRESS }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit --remove-label "dependabot:recreate-in-progress"  ${{ env.PR_IN_PROGRESS }}

      - name: Get List of PRs to Update
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo PR_SUMMARY=$(gh pr list -S "label:dependabot:recreate author:app/dependabot") >> $GITHUB_ENV

      - name: Calc PR to Recreate
        if: ${{ env.PR_SUMMARY }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo PR_TO_RECREATE=$(
            gh pr list -S "label:dependabot:recreate author:app/dependabot" --json number | jq -r 'if .[0] then .[0].number else "" end'
          ) >> $GITHUB_ENV

      - name: Mark Recreate PR to in progress
        if: ${{ env.PR_TO_RECREATE }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit --add-label "dependabot:recreate-in-progress"  ${{ env.PR_TO_RECREATE }}

      - name: Tell Dependabot to Recreate PR
        if: ${{ env.PR_TO_RECREATE }}
        env:
          GH_TOKEN: ${{ secrets.TOKEN_UPDATE_DEPENDABOT }}
        run: |
          gh pr comment -b "@dependabot recreate" ${{ env.PR_TO_RECREATE }}
